# Generated by Django 4.2.6 on 2023-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_menu_remove_menuitem_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(to='menu_app.menuitem'),
        ),
    ]
